image: kolosek/ruby-2.7.2

cache:
  #key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/bundle
    - node_modules
    - public/assets

services:
  - postgres:9.6.10

variables:
  BUNDLE_PATH: vendor/bundle
  DISABLE_SPRING: 1
  DB_HOST: postgres

before_script:
  - gem update bundler
  - rm config/database.yml
  - cp config/database.yml.ci config/database.yml
  - bundle check || bundle install --jobs $(nproc) --path vendor/bundle
  - export RAILS_ENV=test
  # Don't show warnings
  - RUBYOPT="-W0"
  - bundle exec rake db:create
  - bundle exec rake db:test:prepare
  - bundle exec rake db:seed RAILS_ENV='test'

stages:
 - test

rspec:
  stage: test
  script:
    - bundle exec rspec spec/
  artifacts:
    paths:
      - coverage/
      