image: kolosek/ruby-2.7.2

cache:
  #key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/bundle
    - node_modules
    - public/assets

variables:
  BUNDLE_PATH: vendor/bundle
  DISABLE_SPRING: 1
  DB_HOST: postgres
  RUBY_CI_API_URL: apx.ruby.ci
  DISABLE_SPRING: 1

before_script:
  - export RBCI_BUILD_ID="$CI_COMMIT_SHORT_SHA$CI_JOB_ID"
  - export RBCI_COMMIT="$CI_COMMIT_SHA"
  - export RBCI_BRANCH="$CI_COMMIT_REF_NAME"
  - gem update bundler
  - rm config/database.yml
  - cp config/database.yml.ci config/database.yml
  - bundle check || bundle install --jobs $(nproc) --path vendor/bundle
  - export RAILS_ENV=test
  # Don't show warnings
  - RUBYOPT="-W0"
  - bundle exec rake db:create
  - bundle exec rake db:test:prepare
  - bundle exec rake db:seed RAILS_ENV='test'

stages:
 - test

rspec:
  stage: test
  script:
    - bundle exec rspec spec/
  artifacts:
    paths:
      - coverage/
