version: 1
build_packs:
  rails: {}
  ruby:
    version: 3.0.0
  node_js:
    version: 16.18.1
  postgresql:
    version: '12'
  redis:
    version: '6.2'
  # elasticsearch:
  #   version: 7.17.10
  image_magick:
    version: 7.0.10-58
  geckodriver:
    version: 0.29.1